### ISSUE TITLE
Checks fail with duckplyr

### ISSUE THREAD

**Issue by krlmlr** [darwin-eu/PatientProfiles#720]
The duckplyr package is aimed to be a drop-in replacement for dplyr, with full behavior compatibility. To assert that, I'm running checks with a rigged version of dplyr. This package fails its checks in this scenario.

Details: https://github.com/krlmlr/dplyr/blob/f-revdep-duckplyr/revdep/problems.md .

Learn more about duckplyr: https://duckplyr.tidyverse.org/ .

From the error message, I can't tell immediately what the cause of the failure is. I'd appreciate your help: can you please help digest a reproducible example that shows how duckplyr is behaving differently from dplyr in your use case?

The modified dplyr version can be installed with any of:

```r
pak::pak("krlmlr/dplyr@f-revdep-duckplyr")
# remotes::install_github("krlmlr/dplyr@f-revdep-duckplyr")
# devtools::install_github("krlmlr/dplyr@f-revdep-duckplyr")
```

Thanks a lot for your help! Please let me know if you have any questions.

Tracker: https://github.com/tidyverse/duckplyr/issues/297.

**Comment by catalamarti** [comment]
hi @krlmlr I've reduced the error to this simple reprex:

your branch:
``` r
dplyr::tibble(
  x = c(2000L, NA_integer_),
  y = c(1000L, 1000L)
) |>
  dplyr::mutate(new_col = dplyr::if_else(
    .data$x <= .data$y,
    .data$x,
    .data$y
  ))
#> # A tibble: 2 × 3
#>       x     y new_col
#>   <int> <int>   <int>
#> 1  2000  1000    1000
#> 2    NA  1000    1000
```

<sup>Created on 2024-10-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

dplyr current behavior:

``` r
dplyr::tibble(
  x = c(2000L, NA_integer_),
  y = c(1000L, 1000L)
) |>
  dplyr::mutate(new_col = dplyr::if_else(
    .data$x <= .data$y,
    .data$x,
    .data$y
  ))
#> # A tibble: 2 × 3
#>       x     y new_col
#>   <int> <int>   <int>
#> 1  2000  1000    1000
#> 2    NA  1000      NA
```

<sup>Created on 2024-10-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
Will be fixed soon in duckplyr, I no longer see issues with PatientProfiles in the modified dplyr package. Thanks again!
